name: CI unit tests
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  push:
    branches:
      - giskard_library
      - semantic_world_integration
  pull_request:
#    branches:
#      - giskard_library
#      - master
#      - devel
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  docker:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/publish_dockerfiles.yml

  # GitHub Repository-Owners can have uppercase letters.
  # Container Registry URLs need to be lowercase.
  # This job emits a lowercase repo string for container image resolution.
  to-lowercase:
    needs: docker
    runs-on: ubuntu-latest
    outputs:
      repo_lowercase: ${{ steps.lowercase.outputs.repository }}
    steps:
      - id: lowercase
        name: Write lowercase repository output
        run: |
          # Portable lowercase: convert GITHUB_REPOSITORY to lower case and expose as job output
          echo "repository=$(echo \"$GITHUB_REPOSITORY\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

  test:
    needs: to-lowercase
    strategy:
      # Lets all tests finish, even if one test fails
      fail-fast: false
      matrix:
        tests: [ "test_motion_statechart"]
        ubuntu_version: [ "24.04"]
        qp_solver: [ qpSWIFT ]
    runs-on: ubuntu-latest
    container: # Login and start specified container image. Ubuntu20.04 isn't supported on GitHub-Workflow as of 04.2025
      image: ghcr.io/${{ needs.to-lowercase.outputs.repo_lowercase }}:${{ matrix.ubuntu_version }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      QP_SOLVER: ${{ matrix.qp_solver }}
      HOME: /github/home
    steps:
      - name: Set Docker config directory
        run: mkdir -p $HOME/.docker && touch $HOME/.docker/config.json
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: 'giskardpy'
      - name: Checkout semdt repo
        uses: actions/checkout@v4
        with:
          path: 'semantic_digital_twin'
          repository: cram2/semantic_digital_twin
          ref: main
      - name: build semdt
        run: |
          cd semantic_digital_twin
          source /root/venvs/giskardpy/bin/activate
          pip install -r requirements.txt -U
          pip install .
      - name: move pr2.urdf to temp folder from root folder
        run: mv /root/pr2.urdf /__w/giskardpy/giskardpy/giskardpy/resources/urdf/pr2.urdf
      - name: test
        run: |
          cd giskardpy/test
          source /root/venvs/giskardpy/bin/activate
          python3 -m pytest -s ${{ matrix.tests }}
#      - name: Setup upterm session
#  #      if: always()
#        if: failure()
#        uses: lhotari/action-upterm@v1